// ---- GENERATED BY QEDGEN ----
//
// Self-contained Kani proof harnesses for the spec.
//
// These proofs verify the spec's transition design using Kani bounded model
// checking. They operate on a pure model of the state machine (derived from
// the qedspec), independent of framework (Quasar/Anchor) types.
//
//   Lean proves:  transition functions preserve invariants (∀ states)
//   Kani checks:  same properties via bounded model checking + overflow detection
//   Together:     high assurance that the spec design is correct
//
// To run:  cargo kani --harness <name>   (requires cargo-kani)
// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
#![cfg(kani)]

// ============================================================================
// Constants (from qedspec)
// ============================================================================

const BPS_DENOMINATOR: u64 = 10000;
const MAINTENANCE_MARGIN_BPS: u64 = 500;
const MAX_FUNDING_RATE_BPS: u64 = 100;

// ============================================================================
// State model (derived from qedspec — no framework dependencies)
// ============================================================================

#[derive(Clone, Copy)]
struct State {
    is_paused: u8,
    max_leverage: u64,
    protocol_fee_bps: u64,
    max_tvl: u64,
    total_long_oi: u64,
    total_short_oi: u64,
    total_collateral: u64,
    last_funding_at: u64,
    collateral: u64,
    size_usd: u64,
    perp_side: u8,
    perp_size: u64,
    entry_price: u64,
    is_open: u8,
    deposit_amount: u64,
}

// ============================================================================
// Helpers
// ============================================================================

fn mul_div_floor(a: u64, b: u64, c: u64) -> Option<u64> {
    let wide = (a as u128) * (b as u128);
    let result = wide / (c as u128);
    if result > u64::MAX as u128 { None } else { Some(result as u64) }
}

// ============================================================================
// Property predicates (from qedspec properties)
// ============================================================================

fn collateral_conservation(s: &State) -> bool {
    s.total_collateral >= 0 // trivially true for u64
}

fn oi_tracking(s: &State) -> bool {
    s.total_long_oi >= 0 && s.total_short_oi >= 0 // trivially true for u64
}

fn oi_cap(s: &State) -> bool {
    s.total_long_oi.checked_add(s.total_short_oi)
        .map_or(false, |sum| sum <= s.max_tvl)
}

fn leverage_bounds(s: &State) -> bool {
    // None means bound > u64::MAX, so any u64 size_usd is trivially within bounds
    mul_div_floor(s.deposit_amount, s.max_leverage, 1000)
        .map_or(true, |bound| s.size_usd <= bound)
}

fn no_overflow(s: &State) -> bool {
    s.collateral.checked_add(s.size_usd).is_some()
}

// ============================================================================
// Transition functions (from qedspec operations — effects + guards)
//
// Each returns true if the guard passes and the transition fires,
// false if the guard rejects the operation.
// ============================================================================

fn initialize(s: &mut State) -> bool {
    s.is_paused = 0;
    s.total_long_oi = 0;
    s.total_short_oi = 0;
    s.total_collateral = 0;
    true
}

fn atomic_open(s: &mut State, deposit: u64, leverage_bps: u64, perp_side: u8, oracle_price: u64) -> bool {
    let position_size = match mul_div_floor(deposit, leverage_bps, 1000) {
        Some(v) => v,
        None => return false,
    };
    let fee = match mul_div_floor(position_size, s.protocol_fee_bps, BPS_DENOMINATOR) {
        Some(v) => v,
        None => return false,
    };
    let oi_sum = match s.total_long_oi.checked_add(s.total_short_oi) {
        Some(v) => v,
        None => return false,
    };
    if !(s.is_paused == 0
        && deposit > 0
        && leverage_bps <= s.max_leverage
        && leverage_bps >= 1000
        && s.is_open == 0
        && oi_sum.checked_add(position_size).map_or(false, |v| v <= s.max_tvl))
    {
        return false;
    }
    s.is_open = 1;
    s.entry_price = oracle_price;
    s.perp_size = position_size;
    s.size_usd = position_size;
    s.collateral = deposit.saturating_sub(fee);
    s.deposit_amount = deposit;
    if perp_side == 0 {
        s.total_long_oi = s.total_long_oi.saturating_add(position_size);
    } else if perp_side == 1 {
        s.total_short_oi = s.total_short_oi.saturating_add(position_size);
    }
    s.total_collateral = s.total_collateral.saturating_add(deposit);
    true
}

fn atomic_close(s: &mut State, close_bps: u64) -> bool {
    let closing_collateral = match mul_div_floor(s.collateral, close_bps, BPS_DENOMINATOR) {
        Some(v) => v,
        None => return false,
    };
    let closing_size = match mul_div_floor(s.perp_size, close_bps, BPS_DENOMINATOR) {
        Some(v) => v,
        None => return false,
    };
    if !(s.is_open == 1 && close_bps >= 1 && close_bps <= BPS_DENOMINATOR) {
        return false;
    }
    s.collateral = s.collateral.saturating_sub(closing_collateral);
    s.perp_size = s.perp_size.saturating_sub(closing_size);
    s.size_usd = s.size_usd.saturating_sub(closing_size);
    if s.perp_side == 0 {
        s.total_long_oi = s.total_long_oi.saturating_sub(closing_size);
    } else if s.perp_side == 1 {
        s.total_short_oi = s.total_short_oi.saturating_sub(closing_size);
    }
    s.total_collateral = s.total_collateral.saturating_sub(closing_collateral);
    true
}

fn liquidate(s: &mut State, margin_ratio: u64) -> bool {
    if !(s.is_open == 1 && margin_ratio < MAINTENANCE_MARGIN_BPS) {
        return false;
    }
    s.is_open = 0;
    if s.perp_side == 0 {
        s.total_long_oi = s.total_long_oi.saturating_sub(s.perp_size);
    } else if s.perp_side == 1 {
        s.total_short_oi = s.total_short_oi.saturating_sub(s.perp_size);
    }
    s.total_collateral = s.total_collateral.saturating_sub(s.collateral);
    s.collateral = 0;
    s.perp_size = 0;
    s.size_usd = 0;
    true
}

fn settle_funding(s: &mut State, funding_rate_bps: u64, current_timestamp: u64) -> bool {
    if !(s.is_open == 1 && s.is_paused == 0 && funding_rate_bps <= MAX_FUNDING_RATE_BPS) {
        return false;
    }
    s.last_funding_at = current_timestamp;
    true
}

// ============================================================================
// Guard enforcement — transitions reject invalid inputs
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_atomic_open_rejects_invalid() {
    let mut s = State {
        is_paused: kani::any(), max_leverage: kani::any(), protocol_fee_bps: kani::any(),
        max_tvl: kani::any(), total_long_oi: kani::any(), total_short_oi: kani::any(),
        total_collateral: kani::any(), last_funding_at: kani::any(), collateral: kani::any(),
        size_usd: kani::any(), perp_side: kani::any(), perp_size: kani::any(),
        entry_price: kani::any(), is_open: 1, deposit_amount: kani::any(),
    };
    let deposit: u64 = 0; // violates deposit > 0
    let leverage_bps: u64 = kani::any();
    let perp_side: u8 = kani::any();
    let oracle_price: u64 = kani::any();
    assert!(!atomic_open(&mut s, deposit, leverage_bps, perp_side, oracle_price),
        "atomic_open must reject zero deposit");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_settle_funding_rejects_excessive_rate() {
    let mut s = State {
        is_paused: 0, max_leverage: kani::any(), protocol_fee_bps: kani::any(),
        max_tvl: kani::any(), total_long_oi: kani::any(), total_short_oi: kani::any(),
        total_collateral: kani::any(), last_funding_at: kani::any(), collateral: kani::any(),
        size_usd: kani::any(), perp_side: kani::any(), perp_size: kani::any(),
        entry_price: kani::any(), is_open: 1, deposit_amount: kani::any(),
    };
    let funding_rate_bps: u64 = kani::any();
    kani::assume(funding_rate_bps > MAX_FUNDING_RATE_BPS);
    let ts: u64 = kani::any();
    assert!(!settle_funding(&mut s, funding_rate_bps, ts),
        "settle_funding must reject rate > MAX_FUNDING_RATE_BPS");
}

// ============================================================================
// Invariant preservation — transitions preserve spec properties
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_atomic_open_preserves_oi_cap() {
    let mut s = State {
        is_paused: 0, max_leverage: kani::any(), protocol_fee_bps: kani::any(),
        max_tvl: kani::any(), total_long_oi: kani::any(), total_short_oi: kani::any(),
        total_collateral: kani::any(), last_funding_at: 0, collateral: 0,
        size_usd: 0, perp_side: 0, perp_size: 0,
        entry_price: 0, is_open: 0, deposit_amount: 0,
    };
    kani::assume(oi_cap(&s));
    let deposit: u64 = kani::any();
    let leverage_bps: u64 = kani::any();
    let perp_side: u8 = kani::any();
    let oracle_price: u64 = kani::any();
    if atomic_open(&mut s, deposit, leverage_bps, perp_side, oracle_price) {
        assert!(oi_cap(&s), "oi_cap must hold after atomic_open");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_atomic_open_preserves_leverage_bounds() {
    let mut s = State {
        is_paused: 0, max_leverage: kani::any(), protocol_fee_bps: kani::any(),
        max_tvl: kani::any(), total_long_oi: kani::any(), total_short_oi: kani::any(),
        total_collateral: kani::any(), last_funding_at: 0, collateral: 0,
        size_usd: 0, perp_side: 0, perp_size: 0,
        entry_price: 0, is_open: 0, deposit_amount: 0,
    };
    kani::assume(leverage_bounds(&s));
    let deposit: u64 = kani::any();
    let leverage_bps: u64 = kani::any();
    let perp_side: u8 = kani::any();
    let oracle_price: u64 = kani::any();
    if atomic_open(&mut s, deposit, leverage_bps, perp_side, oracle_price) {
        assert!(leverage_bounds(&s), "leverage_bounds must hold after atomic_open");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_settle_funding_preserves_funding_bounds() {
    let mut s = State {
        is_paused: 0, max_leverage: kani::any(), protocol_fee_bps: kani::any(),
        max_tvl: kani::any(), total_long_oi: kani::any(), total_short_oi: kani::any(),
        total_collateral: kani::any(), last_funding_at: kani::any(), collateral: kani::any(),
        size_usd: kani::any(), perp_side: kani::any(), perp_size: kani::any(),
        entry_price: kani::any(), is_open: 1, deposit_amount: kani::any(),
    };
    let funding_rate_bps: u64 = kani::any();
    let ts: u64 = kani::any();
    if settle_funding(&mut s, funding_rate_bps, ts) {
        assert!(funding_rate_bps <= MAX_FUNDING_RATE_BPS,
            "funding_bounds must hold after settle_funding");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_preserves_no_overflow() {
    let mut s = State {
        is_paused: kani::any(), max_leverage: kani::any(), protocol_fee_bps: kani::any(),
        max_tvl: kani::any(), total_long_oi: kani::any(), total_short_oi: kani::any(),
        total_collateral: kani::any(), last_funding_at: kani::any(), collateral: kani::any(),
        size_usd: kani::any(), perp_side: kani::any(), perp_size: kani::any(),
        entry_price: kani::any(), is_open: kani::any(), deposit_amount: kani::any(),
    };
    kani::assume(no_overflow(&s));
    if initialize(&mut s) {
        assert!(no_overflow(&s), "no_overflow must hold after initialize");
    }
}

// ============================================================================
// Cover properties — reachability via kani::cover!
// ============================================================================

#[kani::proof]
#[kani::unwind(3)]
#[kani::solver(cadical)]
fn cover_open_close_path() {
    let mut s = State {
        is_paused: 0, max_leverage: 10000, protocol_fee_bps: 100,
        max_tvl: u64::MAX, total_long_oi: 0, total_short_oi: 0,
        total_collateral: 0, last_funding_at: 0, collateral: 0,
        size_usd: 0, perp_side: 0, perp_size: 0,
        entry_price: 0, is_open: 0, deposit_amount: 0,
    };
    let deposit: u64 = kani::any();
    let leverage_bps: u64 = kani::any();
    let perp_side: u8 = kani::any();
    let oracle_price: u64 = kani::any();
    if atomic_open(&mut s, deposit, leverage_bps, perp_side, oracle_price) {
        kani::cover!(atomic_close(&mut s, BPS_DENOMINATOR), "open then full close is reachable");
    }
}

#[kani::proof]
#[kani::unwind(3)]
#[kani::solver(cadical)]
fn cover_open_liquidate_path() {
    let mut s = State {
        is_paused: 0, max_leverage: 10000, protocol_fee_bps: 100,
        max_tvl: u64::MAX, total_long_oi: 0, total_short_oi: 0,
        total_collateral: 0, last_funding_at: 0, collateral: 0,
        size_usd: 0, perp_side: 0, perp_size: 0,
        entry_price: 0, is_open: 0, deposit_amount: 0,
    };
    let deposit: u64 = kani::any();
    let leverage_bps: u64 = kani::any();
    let perp_side: u8 = kani::any();
    let oracle_price: u64 = kani::any();
    if atomic_open(&mut s, deposit, leverage_bps, perp_side, oracle_price) {
        let margin_ratio: u64 = kani::any();
        kani::cover!(liquidate(&mut s, margin_ratio), "open then liquidate is reachable");
    }
}

// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
