// ---- GENERATED BY QEDGEN ----
//
// Proptest harnesses — property-based testing for the spec's state machine.
// Tier 1 of the verification waterfall: finds counterexamples in milliseconds.
//
//   Proptest: random testing, fast counterexamples (~100ms)
//   Kani:     bounded model checking, exhaustive within bounds (~5-30s)
//   Lean:     mathematical proof, universal guarantees (minutes-hours)
//
// To run:  cargo test --test proptest
// Deep:    PROPTEST_CASES=10000 cargo test --test proptest
// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----

use proptest::prelude::*;

const BPS_DENOMINATOR: u16 = 10000;
const MAINTENANCE_MARGIN_BPS: u16 = 500;
const LIQUIDATION_BONUS_BPS: u16 = 500;
const MAX_FUNDING_RATE_BPS: u8 = 100;
const FUNDING_INTERVAL_SECONDS: u16 = 28800;

#[derive(Debug, Clone, Copy)]
struct State {
    authority: Address,
    fee_recipient: Address,
    is_paused: u8,
    max_leverage: u64,
    protocol_fee_bps: u64,
    max_tvl: u64,
    total_long_oi: u64,
    total_short_oi: u64,
    psf_balance: u64,
    total_collateral: u64,
    last_funding_at: u64,
    owner: Address,
    collateral: u64,
    size_usd: u64,
    perp_side: u8,
    perp_size: u64,
    entry_price: u64,
    is_open: u8,
    deposit_amount: u64,
}

prop_compose! {
    fn arb_State()(authority in prop::array::uniform32(0u8..), fee_recipient in prop::array::uniform32(0u8..), is_paused in 0u8..=255u8, max_leverage in 0u64..=u64::MAX, protocol_fee_bps in 0u64..=u64::MAX, max_tvl in 0u64..=u64::MAX, total_long_oi in 0u64..=u64::MAX, total_short_oi in 0u64..=u64::MAX, psf_balance in 0u64..=u64::MAX, total_collateral in 0u64..=u64::MAX, last_funding_at in 0u64..=u64::MAX, owner in prop::array::uniform32(0u8..), collateral in 0u64..=u64::MAX, size_usd in 0u64..=u64::MAX, perp_side in 0u8..=255u8, perp_size in 0u64..=u64::MAX, entry_price in 0u64..=u64::MAX, is_open in 0u8..=255u8, deposit_amount in 0u64..=u64::MAX) -> State {
        State {
            authority,
            fee_recipient,
            is_paused,
            max_leverage,
            protocol_fee_bps,
            max_tvl,
            total_long_oi,
            total_short_oi,
            psf_balance,
            total_collateral,
            last_funding_at,
            owner,
            collateral,
            size_usd,
            perp_side,
            perp_size,
            entry_price,
            is_open,
            deposit_amount,
        }
    }
}

#[derive(Debug, Clone, Copy)]
struct State {
}

/// Proptest strategy for generating arbitrary State values.
fn arb_state() -> impl Strategy<Value = State> {
    (
,
    ).prop_map(|()| State {
    })
}

/// Boundary-biased strategy for guard rejection tests.
fn arb_boundary_state() -> impl Strategy<Value = State> {
    (
,
    ).prop_map(|()| State {
    })
}

/// collateral_conservation: total_collateral ≥ 0
fn collateral_conservation(s: &State) -> bool {
    total_collateral >= 0
}

/// oi_tracking: total_long_oi ≥ 0 ∧ total_short_oi ≥ 0
fn oi_tracking(s: &State) -> bool {
    (total_long_oi >= 0) && (total_short_oi >= 0)
}

/// oi_cap: total_long_oi + total_short_oi ≤ max_tvl
fn oi_cap(s: &State) -> bool {
    total_long_oi + total_short_oi <= max_tvl
}

/// leverage_bounds: size_usd ≤ (((deposit_amount) * (max_leverage)) / (1000))
fn leverage_bounds(s: &State) -> bool {
    size_usd <= mul_div_floor_u128(deposit_amount, max_leverage, 1000)
}

/// funding_bounds: funding_rate_bps ≤ 100
fn funding_bounds(s: &State) -> bool {
    funding_rate_bps <= 100
}

/// no_overflow: collateral + size_usd ≥ collateral
fn no_overflow(s: &State) -> bool {
    collateral + size_usd >= collateral
}

fn initialize(s: &mut State) -> bool {
    s.authority = authority;
    s.is_paused = 0;
    s.total_long_oi = 0;
    s.total_short_oi = 0;
    s.psf_balance = 0;
    s.total_collateral = 0;
    true
}

fn atomic_open(s: &mut State, deposit: u64, leverage_bps: u64, perp_side: u8) -> bool {
    if !(is_paused == 0 && deposit > 0 && leverage_bps <= max_leverage && leverage_bps >= 1000 && is_open == 0 && total_long_oi + total_short_oi.wrapping_add(position_size) <= max_tvl) {
        return false;
    }
    let position_size = mul_div_floor_u128(deposit, leverage_bps, 1000);
    let fee = mul_div_floor_u128(position_size, protocol_fee_bps, 10000);
    s.is_open = 1;
    s.entry_price = oracle_price;
    s.perp_size = position_size;
    s.size_usd = position_size;
    s.collateral = deposit - fee;
    s.deposit_amount = deposit;
    s.total_long_oi = s.total_long_oi.wrapping_add((if perp_side = 0 then position_size else 0));
    s.total_short_oi = s.total_short_oi.wrapping_add((if perp_side = 1 then position_size else 0));
    s.total_collateral = s.total_collateral.wrapping_add(deposit);
    true
}

fn atomic_close(s: &mut State, close_bps: u64) -> bool {
    if !(is_open == 1 && owner == user && close_bps >= 1 && close_bps <= 10000) {
        return false;
    }
    let closing_collateral = mul_div_floor_u128(collateral, close_bps, 10000);
    let closing_size = mul_div_floor_u128(perp_size, close_bps, 10000);
    let close_fee = mul_div_floor_u128(closing_size, protocol_fee_bps, 10000);
    s.collateral = s.collateral.wrapping_sub(closing_collateral);
    s.perp_size = s.perp_size.wrapping_sub(closing_size);
    s.size_usd = s.size_usd.wrapping_sub(closing_size);
    s.total_long_oi = s.total_long_oi.wrapping_sub((if perp_side = 0 then closing_size else 0));
    s.total_short_oi = s.total_short_oi.wrapping_sub((if perp_side = 1 then closing_size else 0));
    s.total_collateral = s.total_collateral.wrapping_sub(closing_collateral);
    true
}

fn liquidate(s: &mut State) -> bool {
    if !(is_open == 1 && margin_ratio < 500) {
        return false;
    }
    let liq_bonus = mul_div_floor_u128(collateral, 500, 10000);
    let liq_remainder = collateral - liq_bonus;
    s.is_open = 0;
    s.total_long_oi = s.total_long_oi.wrapping_sub((if perp_side = 0 then perp_size else 0));
    s.total_short_oi = s.total_short_oi.wrapping_sub((if perp_side = 1 then perp_size else 0));
    s.total_collateral = s.total_collateral.wrapping_sub(collateral);
    s.collateral = 0;
    s.perp_size = 0;
    s.size_usd = 0;
    true
}

fn settle_funding(s: &mut State, funding_rate_bps: u64) -> bool {
    if !(is_open == 1 && is_paused == 0 && funding_rate_bps <= 100) {
        return false;
    }
    s.last_funding_at = current_timestamp;
    true
}

fn update_config(s: &mut State) -> bool {
    if !(authority == global_config.authority) {
        return false;
    }
    true
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn initialize_preserves_collateral_conservation(s in arb_state()) {
        let mut s = s;
        prop_assume!(collateral_conservation(&s));
        prop_assume!(oi_tracking(&s));
        prop_assume!(oi_cap(&s));
        prop_assume!(leverage_bounds(&s));
        prop_assume!(funding_bounds(&s));
        prop_assume!(no_overflow(&s));
        if initialize(&mut s) {
            prop_assert!(collateral_conservation(&s),
                "collateral_conservation must hold after initialize");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn atomic_open_preserves_collateral_conservation(s in arb_state(), deposit in 0u64..=u64::MAX, leverage_bps in 0u64..=u64::MAX, perp_side in 0u8..=u8::MAX) {
        let mut s = s;
        prop_assume!(collateral_conservation(&s));
        prop_assume!(oi_tracking(&s));
        prop_assume!(oi_cap(&s));
        prop_assume!(leverage_bounds(&s));
        prop_assume!(funding_bounds(&s));
        prop_assume!(no_overflow(&s));
        prop_assume!(s.total_short_oi < s.max_tvl); // strict bound for add
        if atomic_open(&mut s, deposit, leverage_bps, perp_side) {
            prop_assert!(collateral_conservation(&s),
                "collateral_conservation must hold after atomic_open");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn atomic_close_preserves_collateral_conservation(s in arb_state(), close_bps in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(collateral_conservation(&s));
        prop_assume!(oi_tracking(&s));
        prop_assume!(oi_cap(&s));
        prop_assume!(leverage_bounds(&s));
        prop_assume!(funding_bounds(&s));
        prop_assume!(no_overflow(&s));
        if atomic_close(&mut s, close_bps) {
            prop_assert!(collateral_conservation(&s),
                "collateral_conservation must hold after atomic_close");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn liquidate_preserves_collateral_conservation(s in arb_state()) {
        let mut s = s;
        prop_assume!(collateral_conservation(&s));
        prop_assume!(oi_tracking(&s));
        prop_assume!(oi_cap(&s));
        prop_assume!(leverage_bounds(&s));
        prop_assume!(funding_bounds(&s));
        prop_assume!(no_overflow(&s));
        if liquidate(&mut s) {
            prop_assert!(collateral_conservation(&s),
                "collateral_conservation must hold after liquidate");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn settle_funding_preserves_collateral_conservation(s in arb_state(), funding_rate_bps in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(collateral_conservation(&s));
        prop_assume!(oi_tracking(&s));
        prop_assume!(oi_cap(&s));
        prop_assume!(leverage_bounds(&s));
        prop_assume!(funding_bounds(&s));
        prop_assume!(no_overflow(&s));
        if settle_funding(&mut s, funding_rate_bps) {
            prop_assert!(collateral_conservation(&s),
                "collateral_conservation must hold after settle_funding");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn update_config_preserves_collateral_conservation(s in arb_state()) {
        let mut s = s;
        prop_assume!(collateral_conservation(&s));
        prop_assume!(oi_tracking(&s));
        prop_assume!(oi_cap(&s));
        prop_assume!(leverage_bounds(&s));
        prop_assume!(funding_bounds(&s));
        prop_assume!(no_overflow(&s));
        if update_config(&mut s) {
            prop_assert!(collateral_conservation(&s),
                "collateral_conservation must hold after update_config");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn atomic_open_preserves_oi_tracking(s in arb_state(), deposit in 0u64..=u64::MAX, leverage_bps in 0u64..=u64::MAX, perp_side in 0u8..=u8::MAX) {
        let mut s = s;
        prop_assume!(collateral_conservation(&s));
        prop_assume!(oi_tracking(&s));
        prop_assume!(oi_cap(&s));
        prop_assume!(leverage_bounds(&s));
        prop_assume!(funding_bounds(&s));
        prop_assume!(no_overflow(&s));
        prop_assume!(s.total_short_oi < s.max_tvl); // strict bound for add
        if atomic_open(&mut s, deposit, leverage_bps, perp_side) {
            prop_assert!(oi_tracking(&s),
                "oi_tracking must hold after atomic_open");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn atomic_close_preserves_oi_tracking(s in arb_state(), close_bps in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(collateral_conservation(&s));
        prop_assume!(oi_tracking(&s));
        prop_assume!(oi_cap(&s));
        prop_assume!(leverage_bounds(&s));
        prop_assume!(funding_bounds(&s));
        prop_assume!(no_overflow(&s));
        if atomic_close(&mut s, close_bps) {
            prop_assert!(oi_tracking(&s),
                "oi_tracking must hold after atomic_close");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn liquidate_preserves_oi_tracking(s in arb_state()) {
        let mut s = s;
        prop_assume!(collateral_conservation(&s));
        prop_assume!(oi_tracking(&s));
        prop_assume!(oi_cap(&s));
        prop_assume!(leverage_bounds(&s));
        prop_assume!(funding_bounds(&s));
        prop_assume!(no_overflow(&s));
        if liquidate(&mut s) {
            prop_assert!(oi_tracking(&s),
                "oi_tracking must hold after liquidate");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn atomic_open_preserves_oi_cap(s in arb_state(), deposit in 0u64..=u64::MAX, leverage_bps in 0u64..=u64::MAX, perp_side in 0u8..=u8::MAX) {
        let mut s = s;
        prop_assume!(collateral_conservation(&s));
        prop_assume!(oi_tracking(&s));
        prop_assume!(oi_cap(&s));
        prop_assume!(leverage_bounds(&s));
        prop_assume!(funding_bounds(&s));
        prop_assume!(no_overflow(&s));
        prop_assume!(s.total_short_oi < s.max_tvl); // strict bound for add
        if atomic_open(&mut s, deposit, leverage_bps, perp_side) {
            prop_assert!(oi_cap(&s),
                "oi_cap must hold after atomic_open");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn atomic_open_preserves_leverage_bounds(s in arb_state(), deposit in 0u64..=u64::MAX, leverage_bps in 0u64..=u64::MAX, perp_side in 0u8..=u8::MAX) {
        let mut s = s;
        prop_assume!(collateral_conservation(&s));
        prop_assume!(oi_tracking(&s));
        prop_assume!(oi_cap(&s));
        prop_assume!(leverage_bounds(&s));
        prop_assume!(funding_bounds(&s));
        prop_assume!(no_overflow(&s));
        prop_assume!(s.total_short_oi < s.max_tvl); // strict bound for add
        if atomic_open(&mut s, deposit, leverage_bps, perp_side) {
            prop_assert!(leverage_bounds(&s),
                "leverage_bounds must hold after atomic_open");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn settle_funding_preserves_funding_bounds(s in arb_state(), funding_rate_bps in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(collateral_conservation(&s));
        prop_assume!(oi_tracking(&s));
        prop_assume!(oi_cap(&s));
        prop_assume!(leverage_bounds(&s));
        prop_assume!(funding_bounds(&s));
        prop_assume!(no_overflow(&s));
        if settle_funding(&mut s, funding_rate_bps) {
            prop_assert!(funding_bounds(&s),
                "funding_bounds must hold after settle_funding");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn initialize_preserves_no_overflow(s in arb_state()) {
        let mut s = s;
        prop_assume!(collateral_conservation(&s));
        prop_assume!(oi_tracking(&s));
        prop_assume!(oi_cap(&s));
        prop_assume!(leverage_bounds(&s));
        prop_assume!(funding_bounds(&s));
        prop_assume!(no_overflow(&s));
        if initialize(&mut s) {
            prop_assert!(no_overflow(&s),
                "no_overflow must hold after initialize");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn atomic_open_preserves_no_overflow(s in arb_state(), deposit in 0u64..=u64::MAX, leverage_bps in 0u64..=u64::MAX, perp_side in 0u8..=u8::MAX) {
        let mut s = s;
        prop_assume!(collateral_conservation(&s));
        prop_assume!(oi_tracking(&s));
        prop_assume!(oi_cap(&s));
        prop_assume!(leverage_bounds(&s));
        prop_assume!(funding_bounds(&s));
        prop_assume!(no_overflow(&s));
        prop_assume!(s.total_short_oi < s.max_tvl); // strict bound for add
        if atomic_open(&mut s, deposit, leverage_bps, perp_side) {
            prop_assert!(no_overflow(&s),
                "no_overflow must hold after atomic_open");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn atomic_close_preserves_no_overflow(s in arb_state(), close_bps in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(collateral_conservation(&s));
        prop_assume!(oi_tracking(&s));
        prop_assume!(oi_cap(&s));
        prop_assume!(leverage_bounds(&s));
        prop_assume!(funding_bounds(&s));
        prop_assume!(no_overflow(&s));
        if atomic_close(&mut s, close_bps) {
            prop_assert!(no_overflow(&s),
                "no_overflow must hold after atomic_close");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn liquidate_preserves_no_overflow(s in arb_state()) {
        let mut s = s;
        prop_assume!(collateral_conservation(&s));
        prop_assume!(oi_tracking(&s));
        prop_assume!(oi_cap(&s));
        prop_assume!(leverage_bounds(&s));
        prop_assume!(funding_bounds(&s));
        prop_assume!(no_overflow(&s));
        if liquidate(&mut s) {
            prop_assert!(no_overflow(&s),
                "no_overflow must hold after liquidate");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn settle_funding_preserves_no_overflow(s in arb_state(), funding_rate_bps in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(collateral_conservation(&s));
        prop_assume!(oi_tracking(&s));
        prop_assume!(oi_cap(&s));
        prop_assume!(leverage_bounds(&s));
        prop_assume!(funding_bounds(&s));
        prop_assume!(no_overflow(&s));
        if settle_funding(&mut s, funding_rate_bps) {
            prop_assert!(no_overflow(&s),
                "no_overflow must hold after settle_funding");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn update_config_preserves_no_overflow(s in arb_state()) {
        let mut s = s;
        prop_assume!(collateral_conservation(&s));
        prop_assume!(oi_tracking(&s));
        prop_assume!(oi_cap(&s));
        prop_assume!(leverage_bounds(&s));
        prop_assume!(funding_bounds(&s));
        prop_assume!(no_overflow(&s));
        if update_config(&mut s) {
            prop_assert!(no_overflow(&s),
                "no_overflow must hold after update_config");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn atomic_open_rejects_invalid(s in arb_boundary_state(), deposit in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], leverage_bps in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], perp_side in prop_oneof![0u8..=3u8, 252u8..=255u8]) {
        let mut s = s;
        prop_assume!(!(is_paused == 0 && deposit > 0 && leverage_bps <= max_leverage && leverage_bps >= 1000 && is_open == 0 && total_long_oi + total_short_oi.wrapping_add(position_size) <= max_tvl));
        prop_assert!(!atomic_open(&mut s, deposit, leverage_bps, perp_side),
            "atomic_open must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn atomic_close_rejects_invalid(s in arb_boundary_state(), close_bps in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX]) {
        let mut s = s;
        prop_assume!(!(is_open == 1 && owner == user && close_bps >= 1 && close_bps <= 10000));
        prop_assert!(!atomic_close(&mut s, close_bps),
            "atomic_close must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn liquidate_rejects_invalid(s in arb_boundary_state()) {
        let mut s = s;
        prop_assume!(!(is_open == 1 && margin_ratio < 500));
        prop_assert!(!liquidate(&mut s),
            "liquidate must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn settle_funding_rejects_invalid(s in arb_boundary_state(), funding_rate_bps in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX]) {
        let mut s = s;
        prop_assume!(!(is_open == 1 && is_paused == 0 && funding_rate_bps <= 100));
        prop_assert!(!settle_funding(&mut s, funding_rate_bps),
            "settle_funding must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn update_config_rejects_invalid(s in arb_boundary_state()) {
        let mut s = s;
        prop_assume!(!(authority == global_config.authority));
        prop_assert!(!update_config(&mut s),
            "update_config must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn atomic_open_no_overflow_on_total_long_oi(s in arb_state(), deposit in 0u64..=u64::MAX, leverage_bps in 0u64..=u64::MAX, perp_side in 0u8..=u8::MAX) {
        let mut s = s;
        prop_assume!(collateral_conservation(&s));
        prop_assume!(oi_tracking(&s));
        prop_assume!(oi_cap(&s));
        prop_assume!(leverage_bounds(&s));
        prop_assume!(funding_bounds(&s));
        prop_assume!(no_overflow(&s));
        let pre = s.total_long_oi;
        if atomic_open(&mut s, deposit, leverage_bps, perp_side) {
            // If transition succeeded, the add must not have wrapped
            prop_assert!(s.total_long_oi >= pre,
                "overflow: atomic_open.total_long_oi wrapped around after add");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn atomic_open_no_overflow_on_total_short_oi(s in arb_state(), deposit in 0u64..=u64::MAX, leverage_bps in 0u64..=u64::MAX, perp_side in 0u8..=u8::MAX) {
        let mut s = s;
        prop_assume!(collateral_conservation(&s));
        prop_assume!(oi_tracking(&s));
        prop_assume!(oi_cap(&s));
        prop_assume!(leverage_bounds(&s));
        prop_assume!(funding_bounds(&s));
        prop_assume!(no_overflow(&s));
        let pre = s.total_short_oi;
        if atomic_open(&mut s, deposit, leverage_bps, perp_side) {
            // If transition succeeded, the add must not have wrapped
            prop_assert!(s.total_short_oi >= pre,
                "overflow: atomic_open.total_short_oi wrapped around after add");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn atomic_open_no_overflow_on_total_collateral(s in arb_state(), deposit in 0u64..=u64::MAX, leverage_bps in 0u64..=u64::MAX, perp_side in 0u8..=u8::MAX) {
        let mut s = s;
        prop_assume!(collateral_conservation(&s));
        prop_assume!(oi_tracking(&s));
        prop_assume!(oi_cap(&s));
        prop_assume!(leverage_bounds(&s));
        prop_assume!(funding_bounds(&s));
        prop_assume!(no_overflow(&s));
        let pre = s.total_collateral;
        if atomic_open(&mut s, deposit, leverage_bps, perp_side) {
            // If transition succeeded, the add must not have wrapped
            prop_assert!(s.total_collateral >= pre,
                "overflow: atomic_open.total_collateral wrapped around after add");
        }
    }
}

#[derive(Debug, Clone)]
enum Op {
    Initialize,
    AtomicOpen(u64, u64, u8),
    AtomicClose(u64),
    Liquidate,
    SettleFunding(u64),
    UpdateConfig,
}

fn arb_op() -> impl Strategy<Value = Op> {
    prop_oneof![
        Just(Op::Initialize),
        (0u64..=u64::MAX, 0u64..=u64::MAX, 0u8..=u8::MAX).prop_map(|(deposit, leverage_bps, perp_side)| Op::AtomicOpen(deposit, leverage_bps, perp_side)),
        (0u64..=u64::MAX).prop_map(|v| Op::AtomicClose(v)),
        Just(Op::Liquidate),
        (0u64..=u64::MAX).prop_map(|v| Op::SettleFunding(v)),
        Just(Op::UpdateConfig),
    ]
}

fn apply_op(s: &mut State, op: &Op) -> bool {
    match op {
        Op::Initialize => initialize(s),
        Op::AtomicOpen(deposit, leverage_bps, perp_side) => atomic_open(s, *deposit, *leverage_bps, *perp_side),
        Op::AtomicClose(close_bps) => atomic_close(s, *close_bps),
        Op::Liquidate => liquidate(s),
        Op::SettleFunding(funding_rate_bps) => settle_funding(s, *funding_rate_bps),
        Op::UpdateConfig => update_config(s),
    }
}

fn assert_all_properties(s: &State, context: &str) {
    assert!(collateral_conservation(s), "{} violated: collateral_conservation", context);
    assert!(oi_tracking(s), "{} violated: oi_tracking", context);
    assert!(oi_cap(s), "{} violated: oi_cap", context);
    assert!(leverage_bounds(s), "{} violated: leverage_bounds", context);
    assert!(funding_bounds(s), "{} violated: funding_bounds", context);
    assert!(no_overflow(s), "{} violated: no_overflow", context);
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(256))]
    #[test]
    fn state_machine_sequence(ops in proptest::collection::vec(arb_op(), 1..20)) {
        let mut s = State {
        };
        for (i, op) in ops.iter().enumerate() {
            if apply_op(&mut s, op) {
                // Check all properties after each successful transition
                prop_assert!(collateral_conservation(&s),
                    "collateral_conservation violated after op {:?} (step {})", op, i);
                prop_assert!(oi_tracking(&s),
                    "oi_tracking violated after op {:?} (step {})", op, i);
                prop_assert!(oi_cap(&s),
                    "oi_cap violated after op {:?} (step {})", op, i);
                prop_assert!(leverage_bounds(&s),
                    "leverage_bounds violated after op {:?} (step {})", op, i);
                prop_assert!(funding_bounds(&s),
                    "funding_bounds violated after op {:?} (step {})", op, i);
                prop_assert!(no_overflow(&s),
                    "no_overflow violated after op {:?} (step {})", op, i);
            }
        }
    }
}
